upstreamProjects:
  Mule-runtime/mule/4.9.6-WITH-W-18622349
# MULE-18045: Comment public setting to get raml-parser 2 from private repo until it is released in a public repo
# "mavenSettingsXmlId" : "mule-runtime-maven-settings-MuleSettings",
mavenAdditionalArgs: -Dmule.scheduler.alwaysShowSchedulerCreationLocation
additionalConfigFileMetadataProviderList:
  - fileId: mule-runtime-maven-settings-MuleSettings
    variable: org.mule.maven.client.api.SettingsSupplierFactory.userSettings
projectType: runtime
mavenTool: "3.9.9"
jdkTool: OPEN-JDK17
additionalTestConfigs:
  jdk21:
    testJdkTool: TEMURIN-JDK21
