upstreamProjects:
  Mule-runtime/mule/4.5.4
# MULE-18045: Comment public setting to get raml-parser 2 from private repo until it is released in a public repo
# "mavenSettingsXmlId" : "mule-runtime-maven-settings-MuleSettings",
mavenAdditionalArgs: -Dmule.scheduler.alwaysShowSchedulerCreationLocation
additionalConfigFileMetadataProviderList:
  - fileId: mule-runtime-maven-settings-MuleSettings
    variable: org.mule.maven.client.api.SettingsSupplierFactory.userSettings
projectType: runtime
# TODO W-13029381 Change to 17
jdkTool: OPEN-JDK11
mavenAdditionalArgs: -P!testJdkWithoutXmlModule
additionalTestConfigs:
  jdk8:
    testJdkTool: OPEN-JDK8
    mavenAdditionalArgs: ''
# TODO W-13029381 uncomment when default changes to java 17
  #jdk11:
    #testJdkTool: OPEN-JDK11
