upstreamProjects:
  Mule-runtime/mule/master
# MULE-18045: Comment public setting to get raml-parser 2 from private repo until it is released in a public repo
# "mavenSettingsXmlId" : "mule-runtime-maven-settings-MuleSettings",
mavenAdditionalArgs: -Dmule.scheduler.alwaysShowSchedulerCreationLocation
additionalConfigFileMetadataProviderList:
  - fileId: mule-runtime-maven-settings-MuleSettings
    variable: org.mule.maven.client.api.SettingsSupplierFactory.userSettings
projectType: runtime
mavenTool: "3.9.9"
jdkTool: OPEN-JDK17
additionalTestConfigs:
  testNetty:
    mavenAdditionalArgs: -DskipMunitTests -Drevapi.skip -DexportedPackagesValidator.skip -Dmaven.javadoc.skip=true -Dmule.http.service.implementation=NETTY
