upstreamProjects:
  Mule-runtime/mule/support/4.4.x
# MULE-18045: Comment public setting to get raml-parser 2 from private repo until it is released in a public repo
# "mavenSettingsXmlId" : "mule-runtime-maven-settings-MuleSettings",
mavenAdditionalArgs: -X -e -Dmule.scheduler.alwaysShowSchedulerCreationLocation -pl soap-connect/integration-tests
additionalConfigFileMetadataProviderList:
  - fileId: mule-runtime-maven-settings-MuleSettings
    variable: org.mule.maven.client.api.SettingsSupplierFactory.userSettings
projectType: runtime
agentLabel: windows2019-heavy
buildTimeoutTime : 20
buildTimeoutUnit : "MINUTES"

